config/routes.rb
Rails.application.routes.draw do
  resources :megaliths
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/megalith.rb
class Megalith < ApplicationRecord
    # attr_accessor :name

    has_one_attached :photo



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/megaliths_controller.rb
class MegalithsController < ApplicationController
  before_action :set_megalith, only: %i[ show edit update destroy ]

  # GET /megaliths or /megaliths.json
  def index
    @megaliths = Megalith.all
  end

  # GET /megaliths/1 or /megaliths/1.json
  def show
  end

  # GET /megaliths/new
  def new
    @megalith = Megalith.new
  end

  # GET /megaliths/1/edit
  def edit
  end

  # POST /megaliths or /megaliths.json
  def create
    @megalith = Megalith.new(megalith_params)

    respond_to do |format|
      if @megalith.save
        format.html { redirect_to @megalith, notice: "Megalith was successfully created." }
        format.json { render :show, status: :created, location: @megalith }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @megalith.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /megaliths/1 or /megaliths/1.json
  def update
    respond_to do |format|
      if @megalith.update(megalith_params)
        format.html { redirect_to @megalith, notice: "Megalith was successfully updated." }
        format.json { render :show, status: :ok, location: @megalith }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @megalith.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /megaliths/1 or /megaliths/1.json
  def destroy
    @megalith.destroy
    respond_to do |format|
      format.html { redirect_to megaliths_url, notice: "Megalith was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_megalith
      @megalith = Megalith.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def megalith_params
      params.require(:megalith).permit(:name, :address, :city, :category, :description, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/megaliths_helper.rb
module MegalithsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoostrapTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/megaliths/_form.html.erb
<%= form_with(model: megalith, local: true) do |form| %>
  <% if megalith.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(megalith.errors.count, "error") %> prohibited this megalith from being saved:</h2>

      <ul>
        <% megalith.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/megaliths/edit.html.erb
<h1>Editing Megalith</h1>

<%= render 'form', megalith: @megalith %>

<%= link_to 'Show', @megalith %> |
<%= link_to 'Back', megaliths_path %>

app/views/megaliths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Megaliths</h1>

<!-- Call the slideshow -->
<%= render 'shared/slideshow' %>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Category</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @megaliths.each do |megalith| %>
      <tr>
        <td><%= image_tag megalith.photo,  style: 'height:50px;',alt: "..." %></td>
        <td><%= megalith.name %></td>
        <td><%= megalith.address %></td>
        <td><%= megalith.city %></td>
        <td><%= megalith.category %></td>
        <td><%= megalith.description %></td>
        <td><%= megalith.latitude %></td>
        <td><%= megalith.longitude %></td>
        <td><%= link_to 'Show', megalith %></td>
        <td><%= link_to 'Edit', edit_megalith_path(megalith) %></td>
        <td><%= link_to 'Destroy', megalith, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Megalith', new_megalith_path %>

app/views/megaliths/new.html.erb
<h1>New Megalith</h1>

<%= render 'form', megalith: @megalith %>

<%= link_to 'Back', megaliths_path %>

app/views/megaliths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @megalith.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @megalith.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @megalith.city %>
</p>

<p>
  <strong>Category:</strong>
  <%= @megalith.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @megalith.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @megalith.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @megalith.longitude %>
</p>

<%= link_to 'Edit', edit_megalith_path(@megalith) %> |
<%= link_to 'Back', megaliths_path %>

app/views/shared/_slideshow.html.erb
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>